//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicLab.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blood
    {
        public int id { get; set; }
        public int patient { get; set; }
        public int barcode { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual Patient Patient1 { get; set; }
    }
}
