//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicLab.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blood_Service
    {
        public int blood { get; set; }
        public int service { get; set; }
        public string result { get; set; }
        public System.DateTime finished { get; set; }
        public string accepted { get; set; }
        public int id_status { get; set; }
        public int id_analyzer { get; set; }
        public int user { get; set; }
    
        public virtual Analyzer_BloodService Analyzer_BloodService { get; set; }
        public virtual Services Services { get; set; }
        public virtual Status_BloodService Status_BloodService { get; set; }
        public virtual Users Users { get; set; }
    }
}
