//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicLab.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryLogUsers
    {
        public int id { get; set; }
        public int id_user { get; set; }
        public System.DateTime lastenter { get; set; }
        public string status { get; set; }
    
        public virtual Users Users { get; set; }

        public string Login { get { return Users.login; } }
        public string Name { get { return Users.name; } }
    }
}
