//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicLab.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VinidiktovDay3Entities : DbContext
    {
        public VinidiktovDay3Entities()
            : base("name=VinidiktovDay3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Analyzer_BloodService> Analyzer_BloodService { get; set; }
        public virtual DbSet<Blood> Blood { get; set; }
        public virtual DbSet<Blood_Service> Blood_Service { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Insurance_Name> Insurance_Name { get; set; }
        public virtual DbSet<Patient> Patient { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<Social_Type> Social_Type { get; set; }
        public virtual DbSet<Status_BloodService> Status_BloodService { get; set; }
        public virtual DbSet<Type_User> Type_User { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<HistoryLogUsers> HistoryLogUsers { get; set; }
    }
}
