//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicLab.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.Blood = new HashSet<Blood>();
        }
    
        public int id { get; set; }
        public int Type_User { get; set; }
        public string full_name { get; set; }
        public string login { get; set; }
        public string pwd { get; set; }
        public string guid { get; set; }
        public string email { get; set; }
        public int social_sec_number { get; set; }
        public string ein { get; set; }
        public int id_socialType { get; set; }
        public string phone { get; set; }
        public int passport_s { get; set; }
        public int passport_n { get; set; }
        public System.DateTime birthdate_timestamp { get; set; }
        public int id_country { get; set; }
        public int id_insuranceName { get; set; }
        public string insurance_address { get; set; }
        public int insurance_inn { get; set; }
        public string ipadress { get; set; }
        public int insurance_p { get; set; }
        public int insurance_bik { get; set; }
        public string ua { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Blood> Blood { get; set; }
        public virtual Country Country { get; set; }
        public virtual Insurance_Name Insurance_Name { get; set; }
        public virtual Social_Type Social_Type { get; set; }
        public virtual Type_User Type_User1 { get; set; }
    }
}
